import nodemailer from 'nodemailer';

// Create a transporter using Gmail SMTP
// Note: This requires an App Password if using 2FA on Gmail
const transporter = nodemailer.createTransport({
    service: 'gmail',
    auth: {
        user: process.env.SMTP_USER,
        pass: process.env.SMTP_PASS
    }
});

// A professional HTML template for escalating civic issues to local authorities
const getEscalationEmailTemplate = (
    complaintId: string, 
    title: string, 
    description: string, 
    address: string | null, 
    latitude: number, 
    longitude: number, 
    severity: string,
    authorityDetails: string
) => `
<!DOCTYPE html>
<html>
<head>
<style>
  body { font-family: -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, Helvetica, Arial, sans-serif; color: #333; line-height: 1.6; }
  .container { max-width: 600px; margin: 0 auto; padding: 20px; border: 1px solid #eaeaea; border-radius: 8px; }
  .header { background-color: #ef4444; color: white; padding: 15px 20px; border-radius: 8px 8px 0 0; font-weight: bold; font-size: 18px; }
  .content { padding: 20px; background-color: #fafafa; border-radius: 0 0 8px 8px; border: 1px solid #eaeaea; border-top: none; }
  .badge { display: inline-block; padding: 4px 8px; border-radius: 4px; font-weight: bold; font-size: 12px; }
  .badge-CRITICAL { background-color: #fee2e2; color: #991b1b; }
  .badge-HIGH { background-color: #ffedd5; color: #9a3412; }
  .badge-MEDIUM { background-color: #fef3c7; color: #92400e; }
  .badge-LOW { background-color: #f3f4f6; color: #374151; }
  .field { margin-bottom: 15px; }
  .label { font-size: 12px; color: #6b7280; text-transform: uppercase; font-weight: bold; margin-bottom: 4px; display: block; }
  .value { font-size: 15px; margin: 0; }
  .authority-box { background-color: #e0e7ff; border-left: 4px solid #4f46e5; padding: 12px; margin-top: 20px; border-radius: 4px; }
  .map-link { display: inline-block; margin-top: 10px; color: #2563eb; text-decoration: none; font-weight: 500; }
  .footer { margin-top: 20px; font-size: 12px; color: #9ca3af; text-align: center; }
</style>
</head>
<body>
  <div class="container">
    <div class="header">
      🚨 URGENT: Escalated Civic Infrastructure Issue
    </div>
    <div class="content">
      <p>Dear Official,</p>
      <p>This is an automated escalation from the <strong>CivicCore System</strong>. A civic issue in your jurisdiction has been pending for over 10 days without resolution.</p>
      
      <div style="background: white; padding: 15px; border-radius: 6px; border: 1px solid #e5e7eb; margin: 20px 0;">
        <div class="field">
          <span class="label">Issue Title</span>
          <p class="value" style="font-weight: 600;">${title}</p>
        </div>
        
        <div class="field">
          <span class="label">Severity</span>
          <span class="badge badge-${severity}">${severity}</span>
        </div>
        
        <div class="field">
          <span class="label">Location</span>
          <p class="value">${address || 'Address not provided'}</p>
          <a class="map-link" href="https://www.google.com/maps?q=${latitude},${longitude}" target="_blank">📍 View on Google Maps</a>
        </div>
        
        <div class="field">
          <span class="label">Description</span>
          <p class="value" style="white-space: pre-wrap;">${description}</p>
        </div>
      </div>

      <div class="authority-box">
        <span class="label">Routed To:</span>
        <p class="value" style="color: #312e81; font-weight: 500; font-size: 14px;">${authorityDetails}</p>
      </div>

      <p style="margin-top: 20px; font-size: 14px;">Please take immediate action to resolve this issue. Login to the CivicCore administrative portal using Issue ID: <code>${complaintId}</code>.</p>
    </div>
    <div class="footer">
      This email was automatically generated by the CivicCore Automation System.<br>
      © ${new Date().getFullYear()} CivicCore
    </div>
  </div>
</body>
</html>
`;

export async function sendEscalationEmail(
    toEmail: string,
    complaintId: string,
    title: string,
    description: string,
    address: string | null,
    latitude: number,
    longitude: number,
    severity: string,
    authorityDetails: string
) {
    if (process.env.DRY_RUN === 'true') {
        console.log(`[MAILER] [DRY RUN] Would send escalation email to ${toEmail} for complaint ${complaintId}`);
        return true;
    }

    if (!process.env.SMTP_USER || !process.env.SMTP_PASS) {
        console.warn("[MAILER] SMTP_USER or SMTP_PASS not configured. Skipping email send.");
        return false;
    }

    try {
        const mailOptions = {
            from: `"CivicCore System" <${process.env.SMTP_USER}>`,
            to: toEmail,
            subject: `[URGENT] Escalated: 10-Day Pending Issue - ${title}`,
            html: getEscalationEmailTemplate(
                complaintId, title, description, address, latitude, longitude, severity, authorityDetails
            )
        };

        const info = await transporter.sendMail(mailOptions);
        console.log(`[MAILER] Escalation email sent to ${toEmail}. Message ID: ${info.messageId}`);
        return true;
    } catch (error) {
        console.error("[MAILER] Failed to send email:", error);
        return false;
    }
}
